---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(writexl)
library(googledrive)
library(lubridate)
```

#Load data
```{r}
#Capital humano
file_url<-"https://drive.google.com/uc?export=download&id=1d9ahH-uOomyX3akARfcF0o23oR-Jw-59"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path) |> mutate(dni = as.character(dni))->interim_empleados_locacion_min_capital_humano_2024
file.remove( file_content$local_path)

#Jefatura
file_url<-"https://drive.google.com/uc?export=download&id=1ReNNYlFkrCHkMgzarWmLJmh5vD-Fa8Ck"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path) |> mutate(dni = as.character(dni))->interim_empleados_locacion_jefatura_2019_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1VIATAXIijRGlpgStc5gJmK9D20Wzt-dc"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path) |> mutate(dni = as.character(dni))->interim_empleados_certificaciones_jefatura_2024
file.remove( file_content$local_path)


```

```{r}
#Secretaria presidencia
file_url<-"https://drive.google.com/uc?export=download&id=1xBoOriU6NL0TJ6FVxtlaLpC93sBytSyo"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path, guess_max = 2000)->external_empleados_locacion_sec_presidencia_feb_2025
file.remove( file_content$local_path)

#Min Justicia
file_url<-"https://drive.google.com/uc?export=download&id=1KWgR5P-wINKv8OEVfE-SDB4K4zTsjOuL"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path, guess_max = 2000)->external_empleados_locacion_min_justicia_sep_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1stGJv1j3ZHUUunJhfTMVyMzqz084D2QB"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path, guess_max = 2000)->external_empleados_locacion_min_justicia_oct_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1YceJza50P9wpwaba_vJUCznQqzJrqrSR"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path, guess_max = 2000)->external_empleados_locacion_min_justicia_nov_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1DoAiws4kv0ycZLXQx5m3GdEVeTIMddSO"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path, guess_max = 2000)->external_empleados_locacion_min_justicia_dec_2024
file.remove( file_content$local_path)

```


```{r}
#Exteriores

file_url<-"https://drive.google.com/uc?export=download&id=1wLw8Tn2a4nG_fX8M16WhflZUz7838nuA"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path, guess_max = 200)->external_certificaciones_servicios_min_exteriores_sept_dic_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1etuZbkC9cjQGky1AcT6Le6p2bb-Db7cr"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path, guess_max = 200)->external_certificaciones_servicios_min_exteriores_apr_jun_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1i30b5IrquSRJ28qayy6V5G9kvMkcxgWr"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path, guess_max = 200)->external_empleados_locacion_min_exteriores_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1gmTIiQqMdbfZakOWB4KnTMwcc46N7p4G"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path, guess_max = 200)->external_empleados_locacion_min_exteriores_ene_mar_2024
read_xlsx(file_content$local_path, guess_max = 200, sheet = "Renovación Abril a Junio 2024")->external_empleados_locacion_min_exteriores_abr_jun__2024
read_xlsx(file_content$local_path, guess_max = 200, sheet ="Renovación Julio a Sep 2024" )->external_empleados_locacion_min_exteriores_jul_sep_2024
read_xlsx(file_content$local_path, guess_max = 200, sheet ="Renovación Octubre a Dic 2024" )->external_empleados_locacion_min_exteriores_oct_dec_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1d2fIXu-fNClHjhYCtNpmueC4kbRglAJn"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path, guess_max = 200)->external_empleados_locacion_min_exteriores_secin_2023
read_xlsx(file_content$local_path, guess_max = 200, sheet = "UGA")->external_empleados_locacion_min_exteriores_uga_2023
read_xlsx(file_content$local_path, guess_max = 200, sheet = "SCREI")->external_empleados_locacion_min_exteriores_screi_2023
read_xlsx(file_content$local_path, guess_max = 200, sheet = "SECC")->external_empleados_locacion_min_exteriores_secc_2023
read_xlsx(file_content$local_path, guess_max = 200, sheet = "SEREE")->external_empleados_locacion_min_exteriores_seree_2023
read_xlsx(file_content$local_path, guess_max = 200, sheet = "SMAYAS")->external_empleados_locacion_min_exteriores_smayas_2023
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1VwUyrA_g027E4MZ8FnlrAzysZ6w-1fWV"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path, guess_max = 200)->external_empleados_locacion_min_exteriores_altas_2022
read_xlsx(file_content$local_path, guess_max = 200, sheet = "Renovación Año 2022")->external_empleados_locacion_min_exteriores_renovaciones_2022
read_xlsx(file_content$local_path, guess_max = 200, sheet ="RENOVACIONES 2022" )->external_empleados_locacion_min_exteriores_renovaciones_2022_complemento
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1rm23w53IdMH-W8E6_nbFN3TUvYxZ2zpe"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path, guess_max = 200 )->external_empleados_locacion_min_exteriores_renovaciones_complemento
file.remove( file_content$local_path)
```


```{r}
#CONGRESO

#2019-2023 diputados

file_url<-"https://drive.google.com/uc?export=download&id=176QizclrqxKc10sOXFvDGdwrdPDlG8q2"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path) |> 
  mutate(ejercicio = 2019)->external_empleados_diputados_diciembre_2019
read_xlsx(file_content$local_path, sheet = "2020")|> 
  mutate(ejercicio = 2020)->external_empleados_diputados_diciembre_2020
read_xlsx(file_content$local_path, sheet = "2021")|> 
  mutate(ejercicio = 2021)->external_empleados_diputados_diciembre_2021
read_xlsx(file_content$local_path, sheet = "2022")|> 
  mutate(ejercicio = 2022)->external_empleados_diputados_diciembre_2022
read_xlsx(file_content$local_path, sheet = "2023")|> 
  mutate(ejercicio = 2023) |> 
  rename(`NUMERO DE DOCUMENTO` = `NRO DE DOCUMENTO`,
         `FECHA DE INGRESO` =`FECHA INGRESO`,
         `ESTRUCTURA DE DESEMPEÑO`=`ESTRUCTURA DESEMPEÑO`) |> 
  mutate(`NUMERO DE DOCUMENTO` =as.numeric(`NUMERO DE DOCUMENTO`))->external_empleados_diputados_diciembre_2023
file.remove( file_content$local_path)

#Senado 2019-2023
file_url<-"https://drive.google.com/uc?export=download&id=15Yy37iG5bBiXZij01W0h_ErQbw1QPNNi"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)->external_ingresos_hsn_2019_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=15cxhnSdxsleTTJnhZPrOX3hb6FwMvwQS"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)->external_egresos_hsn_2019_2024
file.remove( file_content$local_path)

#Senado sin dni
file_url<-"https://drive.google.com/uc?export=download&id=167z3F1-ixUNc7qoSbgFRIaoQRlYhsjPR"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path)->external_empleados_planta_senado_diciembre_2024_sin_dni
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1ZI0-loN9pFbNv0Xv16HH36e142Oqa7wh"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path)->external_empleados_locacion_senado_diciembre_2024_sin_dni
file.remove( file_content$local_path)

#2024 diputados sin dni
file_url<-"https://drive.google.com/uc?export=download&id=1h3sgy3Muqnz__QtB4bYVjizKwcZ6vwRw"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path)->external_empleados_diputados_septiembre_2024_sin_dni
file.remove( file_content$local_path)

#Biblioteca congreso
file_url<-"https://drive.google.com/uc?export=download&id=1F5_thbImbYFGDdn3Mk44U0vtG-iqBGja"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)->external_empleados_locacion_biblioteca_diciembre_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1kLiZ7jJdrocEYAGF1w0DxLsB6P7HN9tz"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)->external_empleados_planta_biblioteca_diciembre_2024
file.remove( file_content$local_path)


#Das
file_url<-"https://drive.google.com/uc?export=download&id=1fqsE1cdzqX6mCoJ_5zLwfMXjWTKTSpC4"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)->external_empleados_das_congreso_julio_2025
file.remove( file_content$local_path)
```


```{r}
#Ejecutivo (apn)
file_url<-"https://drive.google.com/uc?export=download&id=12j9jZ85Kxu4X6TW7cnhgFEdPT4ETGoz0"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";") |> 
  mutate(doc = as.character(doc))->external_empleados_pen_mayo_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1WSN7IWTyfgVW-4-RWsGbnAasYhEVL5Vk"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";") |> 
  mutate(doc = as.character(doc))->external_empleados_pen_abril_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1IsPHBsP6xU34oIQNa9QSMP3_iUcpWXd0"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";") |> 
  mutate(doc = as.character(doc))->external_empleados_pen_marzo_2025
file.remove( file_content$local_path)


file_url<-"https://drive.google.com/uc?export=download&id=19UARohDVHjzHokMOpFD5mTiyWPmG80Q8"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";") |> 
  mutate(doc = as.character(doc))->external_empleados_pen_febrero_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1-IDOWCDiwp0UiKtqc0o1aTNJx2Yrr7dU"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";") |> 
  mutate(doc = as.character(doc))->external_empleados_pen_diciembre_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1JS5wFMcPEPS6FVqgR5zMN_hOqEVMHbGE"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";") |> 
  mutate(doc = as.character(doc))->external_empleados_pen_noviembre_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1qrMwG_MYoqMUhGnje3-h0juLSpVjwXNq"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";")|> 
  mutate(doc = as.character(doc))->external_empleados_pen_octubre_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1Gm57Tll9eo2RXUIRgiwddetJNQ_hG_Y6"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";")|> 
  mutate(doc = as.character(doc))->external_empleados_pen_septiembre_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1gUPXKYgNz9UqFtgZQiQgVNejTtkPAtdP"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";")|> 
  mutate(doc = as.character(doc))->external_empleados_pen_agosto_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1Q_s-72T71Cr9xYnQfFoxtrquvu_CuuUv"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path,sep=";")->external_empleados_pen_agosto_2023
file.remove( file_content$local_path)


```

```{r}
#Salud
file_url<-"https://drive.google.com/uc?export=download&id=1ikFLEM2bJhVsLjBnEN7mTnPqO9d8ULkP"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path, skip = 2)->external_empleados_locacion_min_salud_2019_2024
file.remove( file_content$local_path)

#Defensa
file_url<-"https://drive.google.com/uc?export=download&id=1bCGTN_u9JikSO8Ap0PbleJHTKUvLNu_p"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)->external_empleados_locacion_min_defensa_2019_Dic_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1FaEiz9-ciw6t3rTRpmr0rfzZrJDbNQxl"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)->external_certificaciones_servicios_min_defensa_sept_2024
read_xlsx(file_content$local_path, sheet = "Octubre")->external_certificaciones_servicios_min_defensa_oct_2024
read_xlsx(file_content$local_path,sheet="Noviembre")->external_certificaciones_servicios_min_defensa_nov_2024
read_xlsx(file_content$local_path,sheet = "Diciembre")->external_certificaciones_servicios_min_defensa_dic_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1iHImo6aZQ6dzvvksGcsTt0IjUU8VFv3C"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path) %>% 
  mutate (...5=as.character(...5)) %>% 
rename(OBSERVACIONES="NOVEDADES DE BAJAS")->external_certificaciones_servicios_min_defensa_mar_2025
read_xlsx(file_content$local_path, sheet = "Abril")%>% 
  mutate (...5=as.character(...5)) %>% 
rename(OBSERVACIONES="NOVEDADES DE BAJAS")->external_certificaciones_servicios_min_defensa_apr_2025
read_xlsx(file_content$local_path,sheet="Mayo")%>%
  mutate (...5=as.character(...5)) %>% 
rename(OBSERVACIONES="NOVEDADES DE BAJAS")->external_certificaciones_servicios_min_defensa_may_2025
read_xlsx(file_content$local_path,sheet = "Junio")%>% 
  mutate (...5=as.character(...5)) %>% 
rename(OBSERVACIONES="NOVEDADES DE BAJAS")->external_certificaciones_servicios_min_defensa_jun_2025
file.remove( file_content$local_path)



#Seguridad
file_url<-"https://drive.google.com/uc?export=download&id=1HginABuQVHiuveqX-7T8o1eiWQ6Sj8q_"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path, sheet= "2020")->external_empleados_locacion_min_seguridad_2020
read_xlsx(file_content$local_path, sheet= "2021")->external_empleados_locacion_min_seguridad_2021
read_xlsx(file_content$local_path, sheet= "2022")->external_empleados_locacion_min_seguridad_2022
read_xlsx(file_content$local_path, sheet= "2023")->external_empleados_locacion_min_seguridad_2023
read_xlsx(file_content$local_path, sheet= "2024")->external_empleados_locacion_min_seguridad_2024
file.remove( file_content$local_path)

#Deporte

file_url<-"https://drive.google.com/uc?export=download&id=16b4LYunoTUMA8w4WbKx0nJM6LQxcI9wG"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path)->external_certificaciones_servicios_sec_deporte_min_interior_sep_dec_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1LDi27SJh_MtRdLWEQfbRlNKzOwS_U_LZ"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path, skip = 3)->external_empleados_locacion_dir_deporte_2024
file.remove( file_content$local_path)

#Ambiente
file_url<-"https://drive.google.com/uc?export=download&id=1ruGGjD-N2Nc3oBKoO1nDgcBmQY4Ljj1g"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)->external_certificaciones_servicios_sec_ambiente_min_interior_sep_dec_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=11rvyMCElYr_fEV_5UfWY_CO0iXjrzeMB"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xls(file_content$local_path, skip = 3)->external_empleados_locacion_dir_ambiente_2024
file.remove( file_content$local_path)

#Min interior
file_url<-"https://drive.google.com/uc?export=download&id=16VKpeciCEzZbq8r4pBYSKS-U94QsKbdf"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path) |> mutate(ejercicio = "2019") |> mutate_all(as.character)->external_empleados_locacion_min_interior_2019
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1uee3VH5-buOr16qt1Afu3XGG53BzP765"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)|> mutate(ejercicio = "2020")|> mutate_all(as.character)->external_empleados_locacion_min_interior_2020
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1neHcI0jvRJOm9XrJ1o5aBSPwUz8hr4hA"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)|> mutate(ejercicio = "2021")|> mutate_all(as.character)->external_empleados_locacion_min_interior_2021
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1Z7tr9sQ4Mu7uJuZDoBjZytreSjwoXP9K"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)|> mutate(ejercicio = "2022")|> mutate_all(as.character)->external_empleados_locacion_min_interior_2022
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1RNohtcEK1oCWhxhFtkM04Fz1lXAoJcFr"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)|> mutate(ejercicio = "2023")|> mutate_all(as.character)->external_empleados_locacion_min_interior_2023
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1dmCp4IUtuzwiYvWb42XR3-yESenzelo3"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)|> mutate(ejercicio = "2024")|> mutate_all(as.character)->external_empleados_locacion_min_interior_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1LM1_aoy4iYVSptJWJWX2e9PEKfJuxwfo"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)|> mutate(ejercicio = "2024")->external_empleados_locacion_min_interior_2019_2024
file.remove( file_content$local_path)


#Vicejefatura de interior
file_url<-"https://drive.google.com/uc?export=download&id=1x8mFjy2gk0N16iLqARr3YFmuJZyUvJZx"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)|> mutate(ejercicio = "2024")->external_certificaciones_servicios_vice_jefatura_min_interior_sep_dec_2024
file.remove( file_content$local_path)

#Deporte, Turismo, Ambiente
file_url<-"https://drive.google.com/uc?export=download&id=114wk1hccMXoeRIwokIwO2_QGRbwX8eXX"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_xlsx(file_content$local_path)->external_certificaciones_servicios_sec_ambiente_turismo_deportes_min_interior_sep_dec_2024
file.remove( file_content$local_path)
```

```{r}
#Judicial

file_url<-"https://drive.google.com/uc?export=download&id=1AWM8OMQ45HBURhRnrkc69aKPFrujAChC"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path)->external_empleados_poder_judicial_abril_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1wD9OsEK6R-yj7-B_sz9uGsIw3IY_Rou7"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path)->external_empleados_poder_judicial_marzo_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1hxHY2K1EqA3UVpM-vLtrhxjsts5ZQWZy"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path)->external_empleados_poder_judicial_enero_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=16OwW5Smkqvtg6bPvw1B2yCjc4L4bhLyc"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path)->external_empleados_poder_judicial_octubre_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1x81giUjOJps-ZM_StbhgElOLdrsgnGQu"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read.csv(file_content$local_path, sep=";")->external_empleados_poder_judicial_septiembre_2024
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1-AOEsr8Hv7BIpBmJ8kxtzF-gKfL0kAGD"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path)->external_empleados_consejo_magistratura_abril_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1zD6J_ITG4z4rd1jj6UUN8gs2v8xiWEAL"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path)->external_empleados_consejo_magistratura_marzo_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1sI3pv-AfnLJirWeYxOsn2ItjwjuIbn6M"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path)->external_empleados_consejo_magistratura_enero_2025
file.remove( file_content$local_path)

file_url<-"https://drive.google.com/uc?export=download&id=1C2NFUx_ocQwHkHQqfJ-w2Qr0DI-yNO5T"
file_content <- drive_download(file = as_id(file_url), overwrite = TRUE)
read_csv(file_content$local_path)->external_empleados_consejo_magistratura_octubre_2024
file.remove( file_content$local_path)
```

#FUNCTIONS
```{r}
remove_accents <- function(text) {
  text %>%
    str_replace_all("Á", "A") %>%
    str_replace_all("É", "E") %>%
    str_replace_all("Í", "I") %>%
    str_replace_all("Ó", "O") %>%
    str_replace_all("Ú", "U")
}
```


```{r}
convert_excel_date <- function(excel_date) {
  excel_date_numeric<-as.numeric(excel_date)

  as.Date(excel_date_numeric, origin = "1899-12-30")
}
```


```{r}
ammend_date<-function(original_dates){
  ammended_dates<-vector()
  
  for (i in 1:length(original_dates)) {
   original_date<-original_dates[i] 
    if(is.na(original_date)){
      ammended_dates[i]<-NA
    }else if(str_detect(original_date,"/")){
      ammended_dates[i]<-as.character(dmy(original_date ))
    }else if(str_detect(original_date,"^\\d{4}")){
      ammended_dates[i]<-as.character( as.Date(as.numeric(original_date), origin = "1899-12-30") )
    }else{
      ammended_dates[i]<-original_date
    }
      
  }
  return(ammended_dates)
  
}
```

```{r}
ammend_date_2<-function(original_dates){
  ammended_dates<-vector()
  
  for (i in 1:length(original_dates)) {
   original_date<-original_dates[i] 
    if(is.na(original_date)){
      ammended_dates[i]<-NA
    }else if(str_detect(original_date,"/|-")){
      ammended_dates[i]<-as.character(dmy(original_date ))
    }else if(str_detect(original_date,"^\\d{4}")){
      ammended_dates[i]<-as.character( as.Date(as.numeric(original_date), origin = "1899-12-30") )
    }else{
      ammended_dates[i]<-original_date
    }
      
  }
  return(ammended_dates)
  
}
```


```{r}
ammend_date_3<-function(original_dates){
  ammended_dates<-as.character( as.Date(as.numeric(original_dates), origin = "1899-12-30") )
  return(ammended_dates)
}
```

#CLEANING

#PL
```{r}
external_empleados_das_congreso_julio_2025 |> 
  rename(dni = DNI, apellido = APELLIDO, nombre=NOMBRE, legajo = LEGAJO, tipo_contratacion = PLANTA,estructura = DIRECCIÓN, ingreso_cargo = `F/INGRESO DAS`) |> 
  select(-ID,-CUIL) |> 
  mutate(nombre_completo = paste(nombre, apellido), organismo = "DAS CONGRESO", poder = "LEGISLATIVO", fuente="PDI", baja_cargo = NA, ultimo_registro_cargo = as.Date("2025-06-30"), categoria_cargo = NA, primer_registro_cargo = ingreso_cargo) |> 
  relocate(dni, nombre_completo, apellido, nombre, legajo, categoria_cargo, tipo_contratacion, organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate(dni = as.character(dni)) |> 
  mutate_if(is.character,str_squish) |> 
  mutate_if(is.character,str_to_upper) |> distinct(dni, .keep_all = TRUE)->interim_empleados_das_congreso_julio_2025
```



```{r}
external_empleados_diputados_septiembre_2024_sin_dni |> 
  distinct(LEGAJO) |> 
  mutate(fecha = as.Date("2024-09-30"))->legajos_empleados_septiembre_2024

#Empleados diputados
bind_rows(external_empleados_diputados_diciembre_2019,external_empleados_diputados_diciembre_2020, external_empleados_diputados_diciembre_2021,
          external_empleados_diputados_diciembre_2022, external_empleados_diputados_diciembre_2023) |> 
  arrange(desc(ejercicio)) |> 
  rename(dni = `NUMERO DE DOCUMENTO`, ingreso_cargo =  `FECHA DE INGRESO`,ultimo_registro_cargo = ejercicio) |> 
  mutate(ultimo_registro_cargo = paste0(ultimo_registro_cargo,"-12-31")) |> 
  mutate(ultimo_registro_cargo =as.Date(ultimo_registro_cargo) ) |> 
  mutate(ingreso_cargo = dmy(ingreso_cargo)) |> 
  distinct(dni, .keep_all = TRUE) |> 
  left_join(legajos_empleados_septiembre_2024, by = "LEGAJO") |> 
  mutate(ultimo_registro_cargo = case_when(
    !is.na(fecha)~ fecha,
    TRUE ~ ultimo_registro_cargo
  )) |> 
  select(-fecha) |> 
  mutate(primer_registro_cargo  =ingreso_cargo, baja_cargo  = NA) |> 
  rename(tipo_contratacion = CONVENIO) |> 
  mutate(tipo_contratacion = case_when(
    str_detect(tipo_contratacion,"PERMANENTE") ~ " PERMANENTE",
    TRUE ~ "TRANSITORIA"
  )) |>
  mutate(organismo = "CAMARA DIPUTADOS") |> 
   mutate(fuente = "WEB DIPUTADOS y PDI", poder="LEGISLATIVO") |> 
  mutate(nombre_completo = paste(NOMBRE, APELLIDO)) |> 
  rename(apellido = APELLIDO, nombre=NOMBRE, categoria_cargo = ESCALAFON,estructura =`ESTRUCTURA DE DESEMPEÑO`, legajo = LEGAJO) |> 

  relocate(dni, nombre_completo, apellido, nombre, legajo, categoria_cargo, tipo_contratacion, organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate(dni = as.character(dni))->interim_empleados_diputados_2019_2024



```

```{r}
#Biblioteca congreso

external_empleados_locacion_biblioteca_diciembre_2024 |> 
  mutate(nombre= str_extract(apellido_y_dni,"(?<=,).+")) |> 
  mutate(apellido = str_remove_all(apellido_y_dni,",.+")) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  select(-apellido_y_dni) |> 
  rename(ingreso_cargo = fecha) |> 
  mutate(ingreso_cargo = as.Date(ingreso_cargo)) |> 
  mutate(dni = str_remove_all(cuil,"^..-|-.$")) |> 
  select(-cuil) |> 
  mutate(organismo = "CONGRESO") |> 
  mutate(estructura = "BIBLIOTECA CONGRESO") |> 
  mutate(tipo_contratacion = "LOCACION") |> 
  #REVISAR ESTA FILA
  mutate(ultimo_registro_cargo = as.Date("2024-12-31")) |> 
  mutate(baja_cargo = NA, primer_registro_cargo = ingreso_cargo) |> 
  relocate(dni, nombre_completo, nombre, apellido, organismo, estructura, tipo_contratacion, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo)->interim_empleados_locacion_biblioteca_diciembre_2024


external_empleados_planta_biblioteca_diciembre_2024 |> 
  mutate(nombre= str_extract(apellido_y_nombre,"(?<=,).+")) |> 
  mutate(apellido = str_remove_all(apellido_y_nombre,",.+")) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  select(-apellido_y_nombre) |> 
  mutate(tipo_contratacion = case_when(
    estado == "P"~ "PERMANENTE", 
    TRUE~ "TRANSITORIA"
  )) |> 
  mutate(organismo = "CONGRESO") |> 
  mutate(estructura = paste(direccion,"BIBLITECA CONGRESO") ) |> 
  select(-direccion, -estado) |> 
  mutate(ingreso_cargo = ammend_date(ingreso)) |> 
  mutate(baja = na_if(baja,"-")) |> 
  mutate(baja = ammend_date(baja)) |> 
  rename(baja_cargo = baja) |> 
  select(-ingreso) |> 
  mutate(ultimo_registro_cargo = case_when(
    !is.na(baja_cargo)~ baja_cargo,
    TRUE ~ "2024-12-31"
  )) |> 
  mutate(ingreso_cargo = as.Date(ingreso_cargo),
         baja_cargo = as.Date(baja_cargo),
         ultimo_registro_cargo = as.Date(ultimo_registro_cargo)) |> 
  mutate(primer_registro_cargo = ingreso_cargo) |> 
  rename(categoria_cargo = categoria) |> 
  relocate(dni, nombre_completo, nombre, apellido,legajo,organismo, estructura, tipo_contratacion, categoria_cargo, ingreso_cargo, baja_cargo, primer_registro_cargo) |> 
  mutate(dni = str_remove_all(dni,"\\."))->interim_empleados_planta_biblioteca_2024

bind_rows(interim_empleados_planta_biblioteca_2024, interim_empleados_locacion_biblioteca_diciembre_2024) |> 
  mutate(categoria_cargo = as.character(categoria_cargo)) |> 
  mutate(fuente = "PDI") |> 
  mutate(poder = "LEGISLATIVO")->interim_empleados_biblioteca_2024
```

```{r}
  external_empleados_locacion_senado_diciembre_2024_sin_dni |> 
   mutate(nombre_completo = str_replace_all(`APELLIDO Y NOMBRE`,"(.+),(.+)","\\2 \\1")) |> 
  relocate(nombre_completo) |> 
  mutate(nombre_completo=str_squish(nombre_completo)) |> 
  distinct(nombre_completo)->auxiliar_nombres_empleados_locacion_diciembre_2024

external_empleados_planta_senado_diciembre_2024_sin_dni |> 
  mutate(nombre_completo = str_replace_all(`APELLIDO Y NOMBRE`,"(.+),(.+)","\\2 \\1")) |> 
  relocate(nombre_completo) |> 
  mutate(nombre_completo=str_squish(nombre_completo)) |> 
  distinct(nombre_completo, LEGAJO)->auxiliar_nombres_empleados_planta_diciembre_2024

bind_rows(auxiliar_nombres_empleados_planta_diciembre_2024, auxiliar_nombres_empleados_locacion_diciembre_2024) |> 
  distinct(nombre_completo, .keep_all = TRUE) |>
  select(nombre_completo, LEGAJO) |> 
  rename(legajo = LEGAJO) |> 
  mutate(fecha = as.Date("2024-12-31"))->auxiliar_empleados_diciembre_2024


#Empleados senado
external_ingresos_hsn_2019_2024 |> 
  left_join(external_egresos_hsn_2019_2024 |> distinct(CUIL, `FECHA FIN`), by ="CUIL") |> 
  mutate(dni = str_remove_all(CUIL,"^..")) |> 
  mutate(dni = str_remove_all(dni,".$")) |> 
  rename(fecha_ingreso = `FECHA INGRESO`,
         fecha_egreso = `FECHA FIN`) ->auxiliar_ingresos_senadores


external_egresos_hsn_2019_2024 |> 
  left_join(external_ingresos_hsn_2019_2024|> distinct(CUIL, `FECHA INGRESO`), by ="CUIL") |> 
  mutate(dni = str_remove_all(CUIL,"^..")) |> 
  mutate(dni = str_remove_all(dni,".$")) |> 
  rename(fecha_ingreso = `FECHA INGRESO`,
         fecha_egreso = `FECHA FIN`) ->auxiliar_egresos_senadores
  
bind_rows(auxiliar_ingresos_senadores, auxiliar_egresos_senadores) |> 
  distinct(dni, .keep_all = TRUE) |> 
  select(-OBSERVACIONES) |> 
  mutate(fecha_ingreso = as.Date(fecha_ingreso), fecha_egreso = as.Date(fecha_egreso)) |> 
  rename(ingreso_cargo = fecha_ingreso,baja_cargo = fecha_egreso) |> 
  mutate(primer_registro_cargo = case_when(
    !is.na(ingreso_cargo)~ingreso_cargo,
    TRUE ~as.Date("2019-01-01")
  )) |> 
  mutate(ultimo_registro_cargo = case_when(
    !is.na(baja_cargo)~baja_cargo,
    TRUE ~as.Date("2024-07-31")
  )) |> 
  mutate(nombre_completo = paste(NOMBRES, APELLIDOS)) |> 
  relocate(nombre_completo) |> 
  mutate(nombre_completo=str_squish(nombre_completo)) |> 
  rename(cuil = CUIL, apellido = APELLIDOS, nombre = NOMBRES, tipo_contratacion = CONVENIO, categoria_cargo = ESCALAFON,estructura =`AREA DESEMPEÑO` ) |> 
  select(-cuil, -`AÑO INGRESO`) |> 
  mutate(tipo_contratacion  = case_when(
    str_detect(tipo_contratacion,"PERMANENTE")~ "PERMANENTE",
    TRUE ~ "TRANSITORIA"
  )) |> 
  mutate(organismo = "SENADO") |> 
  mutate(fuente = "WEB SENADO Y PDI") |> 
  mutate(poder = "LEGISLATIVO") |> 
  left_join(auxiliar_empleados_diciembre_2024, by = "nombre_completo") |> 
  mutate(ultimo_registro_cargo = case_when(
    !is.na(fecha)&is.na(baja_cargo)~ fecha,
    TRUE ~ ultimo_registro_cargo
  )) |> 
  #We fix inconsistencies
  mutate(ultimo_registro_cargo = case_when(
    ingreso_cargo>baja_cargo~ primer_registro_cargo+90,
    TRUE~ ultimo_registro_cargo
  )) |> 
  mutate(baja_cargo = case_when(
    ingreso_cargo>baja_cargo~ NA,
    TRUE~ baja_cargo
  )) |> 
  relocate(dni, nombre_completo, nombre, apellido, legajo,  organismo, estructura, tipo_contratacion, categoria_cargo,ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo) |> 
  select(-fecha)->interim_empleados_senadores_2019_2024
```

```{r}
bind_rows(interim_empleados_das_congreso_julio_2025,interim_empleados_biblioteca_2024, interim_empleados_diputados_2019_2024, interim_empleados_senadores_2019_2024) |> 
  mutate(dni = str_remove_all(dni,",")) |> 
  #OJO NO FILTRAMOS REPETICIONES POR DNI
  #NOS VAMOS A QUEDAR CON TODAS LAS APARICIONES
  #distinct(dni, .keep_all = TRUE) |> 
  mutate_if(is.character,str_to_upper) |>
  mutate_if(is.character,str_squish) |>
  mutate_if(is.character,remove_accents)->processed_empleados_legislativo
```




#Pjn

```{r}

external_empleados_poder_judicial_abril_2025 |> 
  mutate(ultimo_registro_cargo = as.Date("2025-04-30"))->external_empleados_poder_judicial_abril_2025

external_empleados_poder_judicial_marzo_2025 |> 
  mutate(ultimo_registro_cargo = as.Date("2025-03-31"))->external_empleados_poder_judicial_marzo_2025

external_empleados_poder_judicial_enero_2025 |>  mutate(ultimo_registro_cargo = as.Date("2025-01-31"))->external_empleados_poder_judicial_enero_2025

external_empleados_poder_judicial_octubre_2024 |> 
  mutate(fecha_de_nacimiento = dmy(fecha_de_nacimiento)) |> 
  mutate(fecha_de_ingreso = dmy(fecha_de_ingreso)) |> 
  mutate(fecha_ultimo_ascenso = dmy(fecha_ultimo_ascenso)) |> 
   mutate(ultimo_registro_cargo = as.Date("2024-10-31")) ->auxiliar_empleados_poder_judicial_2024

external_empleados_poder_judicial_septiembre_2024 |>
      mutate(fecha_de_ingreso = str_replace(fecha_de_ingreso, "(\\d{4})-(\\d{2})-(\\d{2})", "\\3/\\2/\\1")) |>
      mutate(ultimo_registro_cargo = as.Date("2024-09-30"))|>
      mutate(fecha_de_nacimiento= str_replace(fecha_de_nacimiento, "(\\d{4})-(\\d{2})-(\\d{2})", "\\3/\\2/\\1")) |> 
  mutate(fecha_de_nacimiento = dmy(fecha_de_nacimiento)) |> 
  mutate(fecha_de_ingreso = dmy(fecha_de_ingreso)) |> 
  mutate(fecha_ultimo_ascenso = as.Date(fecha_ultimo_ascenso))->auxiliar_empleados_poder_judicial_septiembre_2024

external_empleados_consejo_magistratura_octubre_2024 |> 
  mutate(fecha_de_nacimiento = dmy(fecha_de_nacimiento)) |> 
  mutate(fecha_de_ingreso = dmy(fecha_de_ingreso)) |> 
  mutate(fecha_ultimo_ascenso = dmy(fecha_ultimo_ascenso)) |> 
   mutate(ultimo_registro_cargo = as.Date("2024-10-31")) ->auxiliar_empleados_consejo_magistratura_octubre_2024
  
  

```


```{r}
#Pjn
external_empleados_poder_judicial_abril_2025 |> 
  bind_rows(external_empleados_poder_judicial_marzo_2025) |> 
  bind_rows(external_empleados_poder_judicial_enero_2025) |> 
  bind_rows(auxiliar_empleados_poder_judicial_2024) |> 
 
  bind_rows(auxiliar_empleados_poder_judicial_septiembre_2024  ) |> 
  distinct(documento_de_identidad_numero, .keep_all = TRUE) |> 

  rename(dni = documento_de_identidad_numero, estructura = reparticion_dependencia_descripcion, cargo = cargo_descripcion, ingreso_cargo = fecha_de_ingreso) |> 
  select(-documento_de_identidad_tipo,-fecha_ultimo_ascenso,-cargo_codigo, -subcargo_codigo,-repartición_.codigo,-`repartición_ codigo`, -dependencia_codigo) |> 
  mutate(apellido_nombre = str_remove_all(apellido_nombre,"(?<=\\s)DE(?=\\s)|(?<=\\s).(?=\\s)|\\(.+\\)")) |> 
  mutate(nombre_completo = case_when(
    str_detect(apellido_nombre,".+\\s.+\\s.+\\s.+$")~ str_replace_all(apellido_nombre,"(.+)\\s(.+)\\s(.+)\\s(.+)$","\\3 \\4 \\1 \\2"),
    str_detect(apellido_nombre,".+\\s.+\\s.+$")~ str_replace_all(apellido_nombre,"(.+)\\s(.+)\\s(.+)$","\\2 \\3 \\1"),
    str_detect(apellido_nombre,".+\\s.+$")~ str_replace_all(apellido_nombre,"(.+)\\s(.+)$","\\2 \\1"),
    TRUE ~ apellido_nombre
  )) |> 
  select(-apellido_nombre) |> 
  mutate(baja_cargo = NA) |> 
  mutate(primer_registro_cargo = ingreso_cargo) |> 
  mutate(organismo = "PODER JUDICIAL") |> 
  mutate(tipo_contratacion = "PERMANENTE") |> 
  relocate(dni, nombre_completo,fecha_de_nacimiento,cargo, tipo_contratacion, organismo, estructura,ingreso_cargo, baja_cargo, primer_registro_cargo,ultimo_registro_cargo )->interim_empleados_pjn_2024

#CM
external_empleados_consejo_magistratura_abril_2025 |>   mutate(ultimo_registro_cargo = as.Date("2025-04-30"))
  bind_rows(external_empleados_consejo_magistratura_marzo_2025 |>  mutate(ultimo_registro_cargo = as.Date("2025-03-31"))  )
  bind_rows( external_empleados_consejo_magistratura_enero_2025 |>  mutate(ultimo_registro_cargo = as.Date("2025-01-31"))  )|> 
  bind_rows(auxiliar_empleados_consejo_magistratura_octubre_2024) |> 
    distinct(documento_de_identidad_numero, .keep_all = TRUE) |> 
    rename(dni = documento_de_identidad_numero, estructura = reparticion_dependencia_descripcion, cargo = cargo_descripcion, ingreso_cargo = fecha_de_ingreso) |> 
  select(-documento_de_identidad_tipo,-fecha_ultimo_ascenso,-cargo_codigo, -subcargo_codigo,-`repartición_ codigo`, -dependencia_codigo) |> 
  mutate(apellido_nombre = str_remove_all(apellido_nombre,"(?<=\\s)DE(?=\\s)|(?<=\\s).(?=\\s)|\\(.+\\)")) |> 
  mutate(nombre_completo = case_when(
    str_detect(apellido_nombre,".+\\s.+\\s.+\\s.+$")~ str_replace_all(apellido_nombre,"(.+)\\s(.+)\\s(.+)\\s(.+)$","\\3 \\4 \\1 \\2"),
    str_detect(apellido_nombre,".+\\s.+\\s.+$")~ str_replace_all(apellido_nombre,"(.+)\\s(.+)\\s(.+)$","\\2 \\3 \\1"),
    str_detect(apellido_nombre,".+\\s.+$")~ str_replace_all(apellido_nombre,"(.+)\\s(.+)$","\\2 \\1"),
    TRUE ~ apellido_nombre
  )) |> 
  select(-apellido_nombre) |> 
  mutate(baja_cargo = NA) |> 
  mutate(primer_registro_cargo = ingreso_cargo) |> 
  mutate(organismo = "CONSEJO MAGISTRATURA") |> 
  mutate(tipo_contratacion = "PERMANENTE") |> 
  relocate(dni, nombre_completo,fecha_de_nacimiento,cargo, tipo_contratacion, organismo, estructura,ingreso_cargo, baja_cargo, primer_registro_cargo,ultimo_registro_cargo )->interim_empleados_cm_2024

bind_rows(interim_empleados_pjn_2024, interim_empleados_cm_2024) |> 
  #Aca si filtramos porque se repite literalmente el mismo cargo
  #con las mismas fechas
  distinct(dni, .keep_all = TRUE) |> 
  mutate(poder = "JUDICIAL", fuente = "CONSEJO MAGISTRATURA") |> 
  mutate(dni = as.character(dni))|> 
  mutate_if(is.character,str_to_upper) |> 
  mutate_if(is.character,remove_accents)->processed_empleados_judicial
```

#EJECUTIVO
```{r}
#Justicia
external_empleados_locacion_min_justicia_dec_2024 |> 
  bind_rows(external_empleados_locacion_min_justicia_nov_2024) |> 
  bind_rows(external_empleados_locacion_min_justicia_oct_2024) |> 
   bind_rows(external_empleados_locacion_min_justicia_sep_2024)->external_empleados_locacion_min_justicia_sep_dec_2024

external_empleados_locacion_min_justicia_sep_dec_2024 |> 
  rename(cuit=CUIL, cargo=CARGO, ultimo_registro_cargo = FECHAEMISION, categoria_cargo = ESCALAFON, ingreso_cargo = FECHA_INGRESO, estructura = DEPENDENCIA, nombre_completo = APELLIDO) |> 
  select(cuit,nombre_completo, cargo, ultimo_registro_cargo, categoria_cargo, ingreso_cargo, estructura) |> 
  distinct(cuit, .keep_all = TRUE) |> 
  mutate(nombre =str_remove_all(nombre_completo,".+,"), apellido = str_remove_all(nombre_completo,",.+")) |> 
  mutate(dni = str_remove_all(cuit,"^..|.$")) |> 
  mutate(ultimo_registro_cargo = as.Date(ultimo_registro_cargo)) |> 
  mutate(primer_registro_cargo = ingreso_cargo) |> 
  mutate(baja_cargo = NA) |> 
  select(-cuit) |> 
  mutate(organismo = "MINISTERIO DE JUSTICIA", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO") |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents)->interim_empleados_min_justicia_2024

```



```{r}
#Exteriores

#2025
external_empleados_locacion_min_exteriores_2025 |> 
  rename(nombre_completo = `Apellido y Nombre`, cuil = Cuil, estructura = SEC, cargo= `Función y Nivel`) |> 
  select(-...1, -Area, -`Cantidad UR`) |> 
  mutate(nombre = str_remove_all(nombre_completo,".+,")) |> 
  mutate(apellido = str_remove_all(nombre_completo,",.+")) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  mutate(categoria_cargo = str_extract(cargo,"(II|I)$")) |>
  mutate(cargo = str_remove_all(cargo,"(II|I)$")) |> 
  mutate(primer_registro_cargo = as.Date("2025-01-01")) |> 
  mutate(ultimo_registro_cargo = as.Date("2025-01-31")) |> 
  mutate(dni = str_remove_all(cuil,"^..|.$")) |> 
  select(-cuil) |> 
  mutate(organismo = "MINISTERIO DE RELACIONES EXTERIORES", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO",
         ingreso_cargo = NA, baja_cargo = NA) |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents)->auxiliar_exteriores_2025

#2024
bind_rows(
external_empleados_locacion_min_exteriores_ene_mar_2024,
external_empleados_locacion_min_exteriores_abr_jun__2024,
external_empleados_locacion_min_exteriores_jul_sep_2024,
external_empleados_locacion_min_exteriores_oct_dec_2024 ) |> 
  filter(!is.na(Cuil)) |> 
  filter(!str_detect(Cuil,"\\D")) |> 
  filter(!str_detect(Período,"DIELA|DNTEC|SECRE|SEREE|UGA")) |> 
  select(-...1,-`Cantidad URS`,-MONTO, -`Resolución Aprobatoria 2024`, -`MONTO FC DE JUNIO`, - ...12,-...13 ,-`MONTO FC JULIO           $ 499.34`,
         -`MONTO FC AGOSTO               $  584.23`,
         -`MONTO FC SEPTIEMBRE          $ 683.55`,
         -`MONTO FC OCTUBRE`,-`Resolución Aprobatoria`,-Area) |> 
   rename(nombre_completo = `Apellido y Nombre`, cuil = Cuil, estructura = SEC, cargo= `Función y Nivel`, periodo = Período) |> 
  mutate(nombre = str_remove_all(nombre_completo,".+,")) |> 
  mutate(apellido = str_remove_all(nombre_completo,",.+")) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  mutate(categoria_cargo = str_extract(cargo,"(II|I)$")) |>
  mutate(cargo = str_remove_all(cargo,"(II|I)$")) |> 
   mutate(dni = str_remove_all(cuil,"^..|.$")) |> 
  select(-cuil) |> 
  mutate(primer_registro_cargo = str_remove_all(periodo,"al.+|a.+|A.+")) |> 
  mutate(primer_registro_cargo = dmy(str_squish(primer_registro_cargo))) |> 
  mutate(ultimo_registro_cargo = str_remove_all(periodo,".+(al|a|A)")) |> 
  mutate(ultimo_registro_cargo = dmy(str_squish(ultimo_registro_cargo))) |> 
  select(-periodo)->provisional_empleados_locacion_min_exteriores_2024

provisional_empleados_locacion_min_exteriores_2024 |> 
  arrange(primer_registro_cargo) |> 
  distinct(dni, .keep_all = TRUE) |> 
  select(dni, primer_registro_cargo)->primeros_registros_exteriores

provisional_empleados_locacion_min_exteriores_2024 |> 
  arrange(desc(ultimo_registro_cargo)) |> 
  distinct(dni, .keep_all = TRUE) |> 
  select(-primer_registro_cargo) |> 
  left_join(primeros_registros_exteriores) |> 
  mutate(organismo = "MINISTERIO DE RELACIONES EXTERIORES", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO",
         ingreso_cargo = NA, baja_cargo = NA) |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents)->auxiliar_exteriores_2024

#2023
bind_rows(
external_empleados_locacion_min_exteriores_secin_2023,
external_empleados_locacion_min_exteriores_uga_2023 |> rename(Area =SEC),
external_empleados_locacion_min_exteriores_screi_2023,
external_empleados_locacion_min_exteriores_secc_2023,
external_empleados_locacion_min_exteriores_seree_2023,
external_empleados_locacion_min_exteriores_smayas_2023) |> 
  select('Apellido y Nombre', Cuil, Área,`Función y Nivel`) |>
  #Ponemos unas fechas aproximadas
  mutate(primer_registro_cargo = as.Date("2023-04-01")) |> 
  mutate(ultimo_registro_cargo = as.Date("2023-10-01")) |> 
  rename(nombre_completo = 'Apellido y Nombre', cuil = Cuil, cargo =`Función y Nivel`, estructura = Área) |> 
  mutate(nombre = str_remove_all(nombre_completo,".+,")) |> 
  mutate(apellido = str_remove_all(nombre_completo,",.+")) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  mutate(categoria_cargo = str_extract(cargo,"(II|I)$")) |>
  mutate(cargo = str_remove_all(cargo,"(II|I)$")) |> 
   mutate(dni = str_remove_all(cuil,"^..|.$")) |> 
   select(-cuil) |> 
  mutate(organismo = "MINISTERIO DE RELACIONES EXTERIORES", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO",
         ingreso_cargo = NA, baja_cargo = NA) |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents) |> 
  distinct(dni, .keep_all =TRUE)->auxiliar_exteriores_2023


#2022
external_empleados_locacion_min_exteriores_altas_2022 |> 
  rename(nombre_completo = `APELLIDO Y NOMBRE`, cuil = CUIT, cargo = `FUNCIÓN Y NIVEL`, estructura = Secretaría, primer_registro_cargo = `Fecha Alta` ) |> 
  select(nombre_completo, cuil, cargo, estructura, primer_registro_cargo) |> 
  mutate(primer_registro_cargo = ammend_date_2(primer_registro_cargo)) |>
  mutate(primer_registro_cargo = as.Date(primer_registro_cargo)) |> 
  #Aproximado
  mutate(ultimo_registro_cargo = as.Date("2022-12-31")) |> 
  mutate(apellido = str_remove(nombre_completo,".+(?=[a-z]\\s[A-Z][A-Z])")) |> 
  mutate(apellido = str_remove_all(apellido,"[a-z]")) |> 
  mutate(nombre = str_remove(nombre_completo,apellido)) |> 
  mutate(dni =str_remove_all(cuil,"^..")) |>
  mutate(dni =str_remove_all(dni,"^-")) |> 
  mutate(dni = str_remove_all(dni,"-.")) |> 
  mutate(dni = str_remove_all(dni,"(?<=.{8}).")) |> 
  select(-cuil) |> 
  mutate(categoria_cargo = str_extract(cargo,"(II|I)$")) |>
  mutate(cargo = str_remove_all(cargo,"(II|I)$")) |> 
  mutate(organismo = "MINISTERIO DE RELACIONES EXTERIORES", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO",
         ingreso_cargo = NA, baja_cargo = NA) |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents)->auxiliar_altas_exteriores_2022
  
external_empleados_locacion_min_exteriores_renovaciones_2022 |> 
  rename(nombre_completo = `APELLIDO Y NOMBRE`, cuil = CUIT, cargo = `FUNCIÓN Y NIVEL`, estructura = Área, primer_registro_cargo = `Período DESDE`, ultimo_registro_cargo = `Período HASTA` ) |> 
  select(nombre_completo, cuil, cargo, estructura, primer_registro_cargo, ultimo_registro_cargo) |> 
  mutate(apellido = case_when(
    str_detect(nombre_completo,",") ~ str_remove_all(nombre_completo, ",.+"),
    str_detect(nombre_completo,"[A-Z][A-Z]") ~ str_remove( str_remove(nombre_completo,".+(?=[a-z]\\s[A-Z][A-Z])"),"[a-z]" ),
    TRUE ~ NA
  )) |> 
  mutate(nombre = str_remove_all(nombre_completo,apellido)) |> 
  mutate(nombre = str_squish( str_remove_all(nombre,"^,"))) |> 
  mutate(apellido = str_squish(apellido)) |> 
   mutate(dni =str_remove_all(cuil,"^..")) |>
  mutate(dni =str_remove_all(dni,"^-")) |> 
  mutate(dni = str_remove_all(dni,"-.")) |> 
  mutate(dni = str_remove_all(dni,"(?<=.{8}).")) |> 
  select(-cuil) |> 
  mutate(primer_registro_cargo = ammend_date_2(primer_registro_cargo)) |> 
  mutate(primer_registro_cargo=as.Date(primer_registro_cargo)) |> 
  mutate(categoria_cargo = str_extract(cargo,"(II|I)$")) |>
  mutate(cargo = str_remove_all(cargo,"(II|I)$")) |> 
  mutate(organismo = "MINISTERIO DE RELACIONES EXTERIORES", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO",
         ingreso_cargo = NA, baja_cargo = NA) |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents) |> 
  filter(!str_detect(dni,"[A-Z]"))->auxiliar_renovacion_exteriores_2022
    
  external_empleados_locacion_min_exteriores_renovaciones_2022_complemento |> 
    select(-...1,-`RESOLUCION APROBATORIA DE LA CONTRATACION 2022`, -Área,-`Honorarios Mensuales en $`) |> 
    rename(movimiento =...2, nombre_completo = `APELLIDO Y NOMBRE`) |> 
    rename(cuil =CUIT, cargo = `FUNCIÓN Y NIVEL`, estructura = Secretaría, fecha = FECHA) |> 
    mutate(dni=str_remove_all(cuil,"^..|.$")) |> 
    mutate(dni = str_remove_all(dni,"^0")) |> 
    mutate(categoria_cargo = str_extract(cargo,"(II|I)$")) |>
  mutate(cargo = str_remove_all(cargo,"(II|I)$")) |> 
    mutate(nombre=str_remove_all(nombre_completo,".+,")) |> 
    mutate(apellido = str_remove_all(nombre_completo,",.+")) |> 
    mutate(ultimo_registro_cargo =case_when(
      str_detect(movimiento,"Renueva")~as.Date("2022-12-31"),
      str_detect(movimiento,"FINALIZADA")~ as.Date("2022-01-31"),
      TRUE ~ NA
    )) |> 
    mutate(primer_registro_cargo = as.Date("2022-01-31")) |> 
  select(-cuil,-movimiento, -fecha) |> 
    mutate(organismo = "MINISTERIO DE RELACIONES EXTERIORES", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO",
         ingreso_cargo = NA, baja_cargo = NA) |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents)->auxiliar_renovacion_exteriores_2022_complemento
  
  auxiliar_renovacion_exteriores_2022_complemento |> 
  bind_rows(auxiliar_renovacion_exteriores_2022) |> 
  distinct(dni, .keep_all = TRUE) |> 
  bind_rows(auxiliar_altas_exteriores_2022) |> 
  distinct(dni, .keep_all = TRUE)->auxiliar_exteriores_2022
  
  #Complemento
  external_empleados_locacion_min_exteriores_renovaciones_complemento |> 
  rename(estado = ESTADO, apellido = APELLIDO, nombre = NOMBRE, cargo = CATEGORIA, ingreso_cargo = FECHA_CONTRATACION, 
         baja_cargo = FECHA_BAJA, cuil = CUIL) |> 
  select(cuil, apellido, nombre, cargo, ingreso_cargo, baja_cargo) |> 
  filter(baja_cargo>ingreso_cargo) |> 
  mutate(primer_registro_cargo = ingreso_cargo,
         ultimo_registro_cargo =baja_cargo) |> 
  mutate(dni = str_remove_all(cuil,"^..|.$")) |> 
  mutate(dni = str_remove_all(dni,"^0")) |> 
  mutate(categoria_cargo = str_extract(cargo,"(II|I)$")) |>
  mutate(cargo = str_remove_all(cargo,"(II|I)$")) |> 
  select(-cuil) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  mutate(organismo = "MINISTERIO DE RELACIONES EXTERIORES", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO", estructura = NA) |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents)->auxiliar_exteriores_complemento
  
  auxiliar_exteriores_complemento |> 
  bind_rows(auxiliar_exteriores_2025,auxiliar_exteriores_2024, auxiliar_exteriores_2023, auxiliar_exteriores_2022)->provisional_cancilleria

provisional_cancilleria|> 
  arrange(primer_registro_cargo) |> 
  distinct(dni, .keep_all = TRUE) |> 
  select(dni, primer_registro_cargo)->primeros_registros_cancilleria

provisional_cancilleria |> 
  distinct(dni, .keep_all = TRUE) |> 
  select(-primer_registro_cargo) |> 
  left_join(primeros_registros_cancilleria) ->interim_empleados_locacion_min_exteriores_2022_2025

#Certificaciones de servicios

bind_rows(external_certificaciones_servicios_min_exteriores_sept_dic_2024, external_certificaciones_servicios_min_exteriores_apr_jun_2025) %>% 
  select(-`Fecha Último Convenio`, -`FECHA ULTIMO CONVENIO`) |> 
  rename(periodo= PERIODO, dni = DNI, nombre_completo = `APELLIDO Y NOMBRE`, estructura = AREA, categoria_cargo=CONVENIO,
         cargo = CATEGORIA) |> 
  mutate(nombre = str_remove_all(nombre_completo,".+,"),
         apellido = str_remove_all(nombre_completo,",.+"),
         nombre_completo=paste(nombre, apellido)
         ) |> 
  mutate(tipo_contratacion = "LOCACION", organismo = "MINISTERIO DE RELACIONES EXTERIORES",
         ingreso_cargo = NA, baja_cargo = NA, fuente = "PDI", poder = "EJECUTIVO") |> 
  mutate(primer_registro_cargo = paste0(str_remove_all(periodo,"..$"),"-",str_remove_all(periodo,"^...."),"-30"  )) |> 
  mutate(primer_registro_cargo=as.Date(primer_registro_cargo)) |> 
  group_by(dni) |> 
  arrange(primer_registro_cargo, .by_group = TRUE) |> 
  select(-periodo) |> 
  ungroup()->auxiliar_certificaciones_servicios_min_exteriores_sept_dic_2024

auxiliar_certificaciones_servicios_min_exteriores_sept_dic_2024 |> 
  group_by(dni) |> 
  slice_tail(n=1) |> 
  rename(ultimo_registro_cargo = primer_registro_cargo) |> 
  select(dni, ultimo_registro_cargo)->ultimos_registros_certificaciones_servicios_min_exteriores_sept_dic_2024
  
  auxiliar_certificaciones_servicios_min_exteriores_sept_dic_2024 |> 
    group_by(dni) |> slice_head(n=1) |> 
    ungroup() |> 
    inner_join(ultimos_registros_certificaciones_servicios_min_exteriores_sept_dic_2024, by ="dni") |> 
    mutate(dni = as.character(dni)) %>% 
    anti_join(interim_empleados_locacion_min_exteriores_2022_2025 %>% 
                distinct(dni))->interim_certificaciones_servicios_min_exteriores_sept_2024_jun_2025
```

```{r}
interim_certificaciones_servicios_min_exteriores_sept_dic_2024 %>% 
  distinct(dni) %>% 
  inner_join(interim_empleados_locacion_min_exteriores_2022_2024)
```


#Salud


```{r}
nombres_columnas_salud<-c("nombre_completo","cuil","cargo","expediente","urs","pago","estructura","primer_registro_cargo","ultimo_registro_cargo","tdr","autoridad")
colnames(external_empleados_locacion_min_salud_2019_2024)<-nombres_columnas_salud

external_empleados_locacion_min_salud_2019_2024 |> 
  select(-expediente, -urs,  -pago, -autoridad, -tdr) |> 
  mutate(dni = str_remove_all(cuil,"^..|.$")) |> 
  relocate(dni, cuil) |> 
  select(-cuil) |> 
  mutate(organismo = "MINISTERIO DE SALUD", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO", apellido = NA, nombre = NA,
         ingreso_cargo = NA, baja_cargo = NA) |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents)->interim_empleados_locacion_min_salud_2019_2024
  
```

#Defensa
```{r}
#Defensa
nombres_columnas_defensa<-c("nombre_completo","ingreso_cargo","baja_cargo","cuil","cargo","categoria_cargo","estructura","firmante","forma_pago","motivo_contratacion","contrato","monto","contrato_2","monto_2","contrato_3","monto_3","contrato_4","monto_4","contrato_5","monto_5")

colnames(external_empleados_locacion_min_defensa_2019_Dic_2024)<-nombres_columnas_defensa

external_empleados_locacion_min_defensa_2019_Dic_2024 |>
  slice(-1) |> 
  slice_head(n=69) |> 
  filter(!is.na(cuil)) |> 
  select(1:7)->auxiliar_defensa_2024

external_empleados_locacion_min_defensa_2019_Dic_2024 |> 
  slice(74:149) |> 
  filter(!is.na(cuil)) |> 
  select(1:7)->auxiliar_defensa_2023

external_empleados_locacion_min_defensa_2019_Dic_2024 |> 
  slice(153:232)|> 
  filter(!is.na(cuil)) |> 
  select(1:7)->auxiliar_defensa_2022

external_empleados_locacion_min_defensa_2019_Dic_2024 |> 
  slice(236:307)|> 
  filter(!is.na(cuil)) |> 
  select(1:7)->auxiliar_defensa_2021

external_empleados_locacion_min_defensa_2019_Dic_2024 |> 
  slice(311:367)|> 
  filter(!is.na(cuil)) |> 
  select(1:7)->auxiliar_defensa_2020

external_empleados_locacion_min_defensa_2019_Dic_2024 |> 
  slice(371:442)|> 
  filter(!is.na(cuil)) |> 
  select(1:7)->auxiliar_defensa_2019


bind_rows(auxiliar_defensa_2024, auxiliar_defensa_2023, auxiliar_defensa_2022,
          auxiliar_defensa_2021, auxiliar_defensa_2020, auxiliar_defensa_2019) |> 
  mutate(ingreso_cargo = convert_excel_date(ingreso_cargo)) |> 
  mutate(baja_cargo = convert_excel_date(baja_cargo))->auxiliar_defensa_2019_2024

auxiliar_defensa_2019_2024 |> 
  arrange(ingreso_cargo) |> 
  distinct(cuil, .keep_all = TRUE) |> 
  select(cuil, ingreso_cargo)->auxiliar_ingresos_defensa

auxiliar_defensa_2019_2024 |> 
  arrange(desc(baja_cargo)) |> 
  #We keep the last registry of each employee
  distinct(cuil, .keep_all = TRUE) |> 
  mutate(baja_cargo = case_when(
    is.na(baja_cargo)~ as.Date("2019-12-31"),
    TRUE~baja_cargo
  )) |> 
  select(-ingreso_cargo) |> 
  #We look for the first date they appeared
  left_join(auxiliar_ingresos_defensa) |> 
  mutate(primer_registro_cargo = ingreso_cargo,
         ultimo_registro_cargo = baja_cargo) |> 
  mutate(dni = str_remove_all(cuil,"\\d\\d-|-\\d")) |> 
  mutate(dni = str_remove_all(dni,"^0")) |> 
  mutate(organismo = "MINISTERIO DE DEFENSA", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO") |> 
  select(dni, nombre_completo, cargo, categoria_cargo,tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents)->interim_empleados_locacion_defensa_2019_2023
  

```


```{r}
#Certificaciones

nombres_columnas_certificaciones_defensa<-c("nombre_completo","cuit","escalafon","categoria_cargo","descartar","estructura","baja","descartar1","registro_cargo","descartar2","descartar3")
bind_rows(external_certificaciones_servicios_min_defensa_sept_2024 |> mutate(registro_cargo = "2024-09-30"),
          external_certificaciones_servicios_min_defensa_oct_2024|> mutate(registro_cargo = "2024-10-31"), 
          external_certificaciones_servicios_min_defensa_nov_2024|> mutate(registro_cargo = "2024-11-30"),
          external_certificaciones_servicios_min_defensa_dic_2024|> mutate(registro_cargo = "2024-12-31"),
          external_certificaciones_servicios_min_defensa_mar_2025 |> mutate(registro_cargo = "2025-03-31"),
          external_certificaciones_servicios_min_defensa_apr_2025|> mutate(registro_cargo = "2025-04-30"), 
          external_certificaciones_servicios_min_defensa_may_2025|> mutate(registro_cargo = "2025-05-31"),
          external_certificaciones_servicios_min_defensa_jun_2025|> mutate(registro_cargo = "2025-06-30")) ->auxiliar_certificaciones

colnames(auxiliar_certificaciones)<-nombres_columnas_certificaciones_defensa
auxiliar_certificaciones |> 
  relocate(registro_cargo) |> 
  select(1:8) |> 
  select(-descartar) |> 
  mutate_if(is.character,str_to_upper) |> 
  mutate_if(is.character,remove_accents) |> 
  mutate(nombre = str_remove_all(nombre_completo,".+,"),
         apellido = str_remove_all(nombre_completo,",.+")) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  mutate(dni = str_remove_all(cuit,"^..-|-.$")) |> 
  select(-cuit) |> 

  mutate(tipo_contratacion = case_when(
    str_detect(escalafon,"^CONTRATO")~ "LOCACION",
    TRUE~ "PLANTA PERMANENTE"
  ) ) |> 
    rename(cargo =escalafon) |> 
  mutate(organismo = "MINISTERIO DE DEFENSA",fuente = "PDI", poder="EJECUTIVO") |> 
  mutate(cargo = case_when(
    str_detect(cargo,"^CONTRATO")~"CONTRATADO",
    TRUE~ cargo
  )) |> 
  mutate(baja = str_remove_all(baja,"[A-Z]|,")) |> 
  mutate(baja = as.character(dmy(baja)) ) |> 
  mutate(cargo = case_when(
    str_detect(categoria_cargo,"ASESOR|ASISTENTE|CONSULTOR")~categoria_cargo,
    TRUE~ cargo
  )) |> 
  mutate(categoria_cargo = case_when(
    str_detect(categoria_cargo,"ASESOR|ASISTENTE|CONSULTOR")~ NA,
    TRUE ~categoria_cargo
  ))->auxiliar_certificaciones_2


  auxiliar_certificaciones_2 |> 
    mutate(ultimo_registro_cargo = as.Date(registro_cargo)) |> 
    arrange(desc(ultimo_registro_cargo)) |> 
    distinct(dni, .keep_all = TRUE) |> 
    select(dni, ultimo_registro_cargo) |> 
    mutate(ultimo_registro_cargo = as.character(ultimo_registro_cargo))->ultimos_registros_certificaciones
  
  auxiliar_certificaciones_2 |> 
    distinct(dni, .keep_all = TRUE) |> 
    left_join(ultimos_registros_certificaciones,by="dni") |> 
      rename(primer_registro_cargo = registro_cargo) |> 
    mutate(ultimo_registro_cargo = case_when(
      !is.na(baja)~ baja,
      TRUE ~ ultimo_registro_cargo
    )) |> 
    mutate(ingreso_cargo = NA) |> 
    rename(baja_cargo = baja) |> 
    mutate(baja_cargo=as.Date(baja_cargo,),
           ingreso_cargo=as.Date(ingreso_cargo),
           ultimo_registro_cargo = as.Date(ultimo_registro_cargo),
           primer_registro_cargo=as.Date(primer_registro_cargo))->interim_certificaciones_servicios_min_defensa_sept_dic_2024
  
```

#Seguridad
```{r}
external_empleados_locacion_min_seguridad_2021 |> 
  mutate(`Fecha Finalización`=na_if(`Fecha Finalización`,"-")) |> 
  mutate(`Fecha Finalización` = convert_excel_date(`Fecha Finalización`)) |> 
  mutate(`Fecha Finalización` = as.POSIXct(`Fecha Finalización`))->external_empleados_locacion_min_seguridad_2021

external_empleados_locacion_min_seguridad_2020 |> 
  mutate(`Fecha Finalización` = ammend_date(`Fecha Finalización`)) |> 
  mutate(`Fecha Finalización` = as.POSIXct(`Fecha Finalización`, format = "%Y-%m-%d"))->external_empleados_locacion_min_seguridad_2020


bind_rows(external_empleados_locacion_min_seguridad_2024, external_empleados_locacion_min_seguridad_2023, external_empleados_locacion_min_seguridad_2022, 
          external_empleados_locacion_min_seguridad_2021, external_empleados_locacion_min_seguridad_2020) |> 
  select(-`N° contrato`, -`Detalle de servicios prestados`,-`Nombre del funcionario firmante`,-`Forma de pago`,-`Servicios prestados`,-`Detalle de servicios prestados (cronograma de trabajo)`) |> 
  rename(cuit = `Cuit Contratista`) |> 
  mutate(dni = str_remove_all(cuit,"^..|.$")) |> 
  mutate(dni =str_remove_all(dni,"^0")) |> 
  select(-cuit) |> 
  rename(ingreso_cargo =`Fecha de inicio`,baja_cargo = `Fecha Finalización`,
         contratista = `Nombre el contratista`, cargo = `Objeto del Contrato`, estructura = `Dependencia / área de prestación de servicios`) |> 
  relocate(dni) |> 
  mutate(nombre = str_remove_all(contratista,".+,")) |> 
  mutate(apellido = str_remove_all(contratista,",.+")) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  select(-contratista) |> 
  mutate(ingreso_cargo = as.Date(ingreso_cargo), baja_cargo= as.Date(baja_cargo)) |> 
  arrange(desc(baja_cargo))->auxiliar_empleados_min_seguridad_2020_2024

auxiliar_empleados_min_seguridad_2020_2024 |> 
  arrange(ingreso_cargo) |> 
  distinct(dni,  .keep_all = TRUE) |> 
  select(dni, ingreso_cargo)->auxiliar_ingresos


auxiliar_empleados_min_seguridad_2020_2024 |> 
  distinct(dni, .keep_all = TRUE) |> 
  select(-ingreso_cargo) |> 
  left_join(auxiliar_ingresos) |> 
  rename(ultimo_registro_cargo = baja_cargo) |> 
  mutate(baja_cargo = NA) |> 
  mutate(primer_registro_cargo = ingreso_cargo) |> 
  mutate(organismo = "MINISTERIO DE SEGURIDAD", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO") |> 
  select(dni, nombre_completo, apellido, nombre, cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
  mutate_if(is.character,remove_accents)->interim_empleados_locacion_seguridad_2020_2024
  
```
#Min interior
```{r}
bind_rows(external_empleados_locacion_min_interior_2024, external_empleados_locacion_min_interior_2023, external_empleados_locacion_min_interior_2022,
          external_empleados_locacion_min_interior_2021, external_empleados_locacion_min_interior_2020, external_empleados_locacion_min_interior_2019) |> 
  select(-`Nro. de SAF`,-`CUIT Organismo`,-`Descr. de Escalafón`, -`Nro. de Programa`,-CUIL, -`Sist. de Acceso/ Mod. de Vinc.`,-`Sist. de Acceso/Mod. de Vinc.`) |> 
  rename(organismo = Organismo, dni =DNI, apellido = Apellidos, nombre = Nombres,cargo = `Nivel/Categoría`,secretaria = Secretaría, subsecreataria = Subsecretaría , direccion = `Dirección Nacional/General`,jurisdiccion =Jurisdicción, jerarquia = Grado) |> 
  mutate(organismo = case_when(
    is.na(organismo)~ jurisdiccion,
    TRUE ~ organismo
  )) |> 
  select(-jurisdiccion) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  mutate(categoria_cargo = str_extract(cargo,"II|I") ) |> 
  mutate(categoria_cargo = case_when(
    is.na(categoria_cargo)~ jerarquia,
    TRUE ~ categoria_cargo
  )) |> 
  select(-jerarquia) |> 
  mutate(cargo = str_squish(str_remove_all(cargo,"II$|I$")) ) |> 
  rename(estructura = secretaria) |> 
  mutate(estructura = na_if(estructura,"-")) |> 
  mutate(estructura = case_when(
    is.na(estructura)~ subsecreataria,
    TRUE ~ estructura
  )) |> 
  select(-subsecreataria,-direccion) |> 
  mutate(registro_cargo = as.Date(paste0(ejercicio,"-12-31")))->auxiliar_empleados_locacion_interior

auxiliar_empleados_locacion_interior |> 
  arrange(registro_cargo) |> 
  distinct(dni, .keep_all = TRUE) |> 
  mutate(primer_registro_cargo = as.Date(paste0(ejercicio,"-01-31"))) |> 
  select(dni, primer_registro_cargo)->ingresos_min_interior

auxiliar_empleados_locacion_interior |> 
  arrange(desc(registro_cargo)) |> 
  distinct(dni, .keep_all = TRUE) |> 
  rename(ultimo_registro_cargo = registro_cargo) |> 
  select(-ejercicio) |> 
  left_join(ingresos_min_interior) |> 
  mutate(tipo_contratacion = "LOCACION") |> 
  mutate(poder = "EJECUTIVO") |> 
  mutate(fuente = "PDI") |> 
  mutate(ingreso_cargo = NA, baja_cargo = NA) |> 
  mutate_if(is_character,str_to_upper) |> 
  relocate(dni, nombre_completo,apellido, nombre,cargo, categoria_cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character,remove_accents)->interim_empleados_locacion_min_interior_2019_2024


external_certificaciones_servicios_vice_jefatura_min_interior_sep_dec_2024 |> 
  rename(ultimo_registro_cargo = `Fecha de Emisión`, nombre_completo = `Nombre y Apellido del Agente`, dni = `DNI y/o CUIL`,
         cargo = `Cargo desempeñado`, tipo_contratacion = `Modalida de contratación`, ingreso_cargo = `Fecha de ingreso`,
         estructura = `Unidad, Dependecia o área de desempeño`) |> 
  select(-`Número de Certificación`,- ejercicio) |> 
  arrange(desc(ultimo_registro_cargo)) |> 
  distinct(dni,.keep_all = TRUE) |> 
  mutate(nombre = str_remove_all(nombre_completo,".+,"), apellido =  str_remove_all(nombre_completo,",.+"), 
         baja_cargo = NA) |> 
  mutate(tipo_contratacion = case_when(
    str_detect(tipo_contratacion,"SINEP|Permanente")~"PLANTA PERMANENTE",
    str_detect(tipo_contratacion,"TRANSITORIA|Autoridad Superior|Transitoria")~"PLANTA TRANSITORIA",
    TRUE ~ NA
    
  )) |> 
  mutate(organismo = "JEFATURA DE GABINETE - VICEJEFATURA DEL INTERIOR", primer_registro_cargo = ingreso_cargo, poder = "EJECUTIVO", fuente = "PDI") |> 
  relocate(dni, nombre_completo,apellido, nombre,cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
   mutate_if(is.character,remove_accents) |> 
  mutate(dni = as.character(dni))->interim_certificaciones_servicios_vice_jefatura_min_interior_sep_dec_2024


bind_rows(interim_certificaciones_servicios_vice_jefatura_min_interior_sep_dec_2024,interim_empleados_locacion_min_interior_2019_2024 ) |> 
  distinct(dni, .keep_all = TRUE)->interim_empleados_ministerio_interior


```



#Dir deportes

```{r}

external_certificaciones_servicios_sec_deporte_min_interior_sep_dec_2024 |> 
  rename(ultimo_registro_cargo = `FECHA DE EMISIÓN`, cuit = CUIL, nombre_completo = `NOMBRE Y APELLIDO`,
         cargo = `CARGO DESEMPEÑADO`, estructura = DEPENDENCIA, ingreso_cargo = `FECHA INGRESO`, baja_cargo  = OBSERVACIONES, tipo_contratacion = `MODALIDAD DE CONTRTACIÓN`) |> 
  select(-`NÚMERO DE CERTIFICACIÓN`) |> 
  mutate(dni = str_remove_all(cuit,"^..|.$")) |> 
  mutate(dni = str_remove_all(dni,"^0")) |> 
   select(-cuit) |> 
  mutate(nombre = str_remove_all(nombre_completo,".+,"), apellido =  str_remove_all(nombre_completo,",.+"), 
         baja_cargo = dmy(str_remove_all(baja_cargo,"[a-zA-Z]"))) |> 
  mutate(tipo_contratacion = case_when(
    str_detect(tipo_contratacion,"SINEP")~"PLANTA PERMANENTE",
    str_detect(tipo_contratacion,"TRANSITORIA")~"PLANTA TRANSITORIA",
    TRUE ~ "LOCACION"
    
  )) |> 
  mutate(ultimo_registro_cargo = case_when(
    !is.na(baja_cargo)~ baja_cargo,
    TRUE ~ ultimo_registro_cargo
  )) |> 
  mutate(organismo = "JEFATURA DE GABINETE - SEC DEPORTE", primer_registro_cargo = ingreso_cargo, poder = "EJECUTIVO", fuente = "PDI") |> 
  relocate(dni, nombre_completo,apellido, nombre,cargo, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
   mutate_if(is.character,remove_accents)->interim_empleados_planta_locacion_deporte_2024

external_empleados_locacion_dir_deporte_2024 |> 
  select(-`MONTO TOTAL DEL CONTRATO`,-`DETALLE DE LOS SERVICIOS PRESTADOS`, -`NORMBRE DEL FUNCIONARIO QUE FIRMÓ EL CONTRATO`,-`FORMA DE PAGO`,-`ADENDAS O MODIFICACIONES`, -`CUIT DEL CONTRATISTA`,-`NOMBRE DEL CONTRATISTA`) |>
  rename(apellido = APELLIDO, nombre = NOMBRE, cuit = CUIL, ingreso_cargo = `FECHA DE INICIO DEL CONTRATO`,baja_cargo =  `FECHA DE FINALIZACIÓN DEL CONTRATO`, estructura = `DEPENDENCIA O ÁREA QUE SOLICITÓ EL SERVICIO`) |> 
  mutate(dni = str_remove_all(cuit,"^..|.$")) |> 
  mutate(dni = str_remove_all(dni,"^0")) |> 
  select(-cuit) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  mutate(organismo = "JEFATURA DE GABINETE - SEC DEPORTE", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO")->auxiliar_empleados_locacion_dir_deporte_2024

auxiliar_empleados_locacion_dir_deporte_2024 |> 
  arrange(ingreso_cargo) |>
   distinct(dni, .keep_all = TRUE) |> 
  select(dni, ingreso_cargo)->auxiliar_ingresos_deporte

auxiliar_empleados_locacion_dir_deporte_2024 |> 
  arrange(desc(baja_cargo)) |> 
  distinct(dni, .keep_all = TRUE) |> 
  select(-ingreso_cargo) |> 
  left_join(auxiliar_ingresos_deporte) |> 
  mutate(ingreso_cargo=as.Date(ingreso_cargo), baja_cargo = as.Date(baja_cargo)) |> 
  mutate(primer_registro_cargo = ingreso_cargo, ultimo_registro_cargo = baja_cargo) |>
  relocate(dni, nombre_completo,apellido, nombre, tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
   mutate_if(is.character,remove_accents)->interim_empleados_locacion_deporte_2024

bind_rows(interim_empleados_planta_locacion_deporte_2024, interim_empleados_locacion_deporte_2024) |> 
  distinct(dni, .keep_all = TRUE)->interim_empleados_deporte_2024

```

#Ambiente
```{r}

external_certificaciones_servicios_sec_ambiente_min_interior_sep_dec_2024 |> 
  rename(ultimo_registro_cargo = `Fecha de Emisión`, cuit = CUIL, nombre_completo = `Nombre y Apellido`,
         cargo = `Cargo desempeñado`, estructura = Dependencia, ingreso_cargo = `Fecha de Ingreso`, tipo_contratacion = `Modalidad de contratación`) |> 
  select(-`Número de Certificación`) |> 
  mutate(dni = str_remove_all(cuit,"^..|.$")) |> 
  mutate(dni = str_remove_all(dni,"^0")) |> 
   select(-cuit) |> 
  mutate(nombre = str_remove_all(nombre_completo,".+,"), apellido =  str_remove_all(nombre_completo,",.+")) |> 
  mutate(tipo_contratacion = case_when(
    str_detect(tipo_contratacion,"SINEP")~"PLANTA PERMANENTE",
    str_detect(tipo_contratacion,"TRANSITORIA")~"PLANTA TRANSITORIA",
    TRUE ~ "LOCACION"
  )) |> 
  mutate(baja_cargo = NA, organismo = "JEFATURA DE GABINETE - SEC AMBIENTE", primer_registro_cargo = ingreso_cargo, poder = "EJECUTIVO", fuente = "PDI") |> 
  relocate(dni, nombre_completo,apellido, nombre, cargo,tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper) |> 
   mutate_if(is.character,remove_accents)->interim_empleados_planta_locacion_ambiente_2024


external_empleados_locacion_dir_ambiente_2024 |> 
  select(-`MONTO TOTAL DEL CONTRATO`,-`DETALLE DE LOS SERVICIOS PRESTADOS`, -`NORMBRE DEL FUNCIONARIO QUE FIRMÓ EL CONTRATO`,-`FORMA DE PAGO`,-`ADENDAS O MODIFICACIONES`, -`CUIT DEL CONTRATISTA`,-`NOMBRE DEL CONTRATISTA`) |>
  rename(apellido = APELLIDO, nombre = NOMBRE, cuit = CUIL, ingreso_cargo = `FECHA DE INICIO DEL CONTRATO`,baja_cargo =  `FECHA DE FINALIZACIÓN DEL CONTRATO`, estructura = `DEPENDENCIA O ÁREA QUE SOLICITÓ EL SERVICIO`) |> 
  mutate(dni = str_remove_all(cuit,"^..|.$")) |> 
  mutate(dni = str_remove_all(dni,"^0|-")) |> 
  select(-cuit) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  mutate(organismo = "JEFATURA DE GABINETE - SEC AMBIENTE", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO")->auxiliar_empleados_locacion_dir_ambiente_2024

auxiliar_empleados_locacion_dir_ambiente_2024 |> 
  arrange(ingreso_cargo) |>
   distinct(dni, .keep_all = TRUE) |> 
  select(dni, ingreso_cargo)->auxiliar_ingresos_ambiente

auxiliar_empleados_locacion_dir_ambiente_2024 |> 
  arrange(desc(baja_cargo)) |> 
  distinct(dni, .keep_all = TRUE) |> 
  select(-ingreso_cargo) |> 
  left_join(auxiliar_ingresos_ambiente) |> 
  mutate(ingreso_cargo=as.Date(ingreso_cargo), baja_cargo = as.Date(baja_cargo),cargo = NA) |> 
  mutate(primer_registro_cargo = ingreso_cargo, ultimo_registro_cargo = baja_cargo) |>
   relocate(dni, nombre_completo, apellido, nombre,  cargo,   tipo_contratacion, organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo) |>
  mutate_if(is.character, str_to_upper)|> 
   mutate_if(is.character,remove_accents)->interim_empleados_locacion_ambiente_2024


bind_rows(interim_empleados_planta_locacion_ambiente_2024, interim_empleados_locacion_ambiente_2024) |> 
  distinct(dni, .keep_all = TRUE)->interim_empleados_ambiente_2024
```
#Turismo, ambiente, deportes
```{r}
external_certificaciones_servicios_sec_ambiente_turismo_deportes_min_interior_sep_dec_2024 |> 
  rename(ultimo_registro_cargo = `Fecha creación`,nombre_completo = Referencia, tipo_contratacion = `tipo de contratacion`,
         cuit = cuil,cargo = funcion,ingreso_cargo = `fecha ingreso`) |> 
  select(-`Número GDE`,-`Número especial`,-`Usuario generador`, -`Tipo doc.`) |> 
  mutate(ultimo_registro_cargo =dmy( str_remove_all(ultimo_registro_cargo,"\\d\\d:.+")) ) |> 
  mutate(nombre_completo = str_remove_all(nombre_completo,"Certificado de servicios agente |Certificación de Servicios de las Abogadas|Certificación de servicios agente|SITUACION DE REVISTA|Certificado agente|Certificado laboral agente|Certificado laboral|Informe agente|	Certificación de servicios agente|CERTIFICACION DE SERVICIOS|Sr\\.|Ing\\.|Certificación de la abogada|Certificación de las abogadas|	CERTIFICACIÓN DE SERVICIOS|Certificacion de Servicios Dra\\.|Certificación de revista|SITUACIÓN DE REVISTA|CERTIFICACIÓN DE SERVICIOS")) |> 
  mutate(nombre_completo = str_remove_all(nombre_completo,"Licenciado|Abogado|Sra\\.|Certificación de Servicios")) |> 
   mutate(nombre_completo = str_remove_all(nombre_completo,"Certificacion de Servicios Agente|Certificación de servicios|certificación de servicios abogado|Srta\\.|Agente|Dra\\.|-|–")) |> 
  filter(!is.na(cuit)) |> 
  mutate(dni = str_remove_all(cuit,"^\\d\\d-|-\\d")) |> 
  select(-cuit) |> 
  mutate(tipo_contratacion = case_when(
    str_detect(tipo_contratacion,"permanente")~"PLANTA PERMANENTE",
    str_detect(tipo_contratacion,"transitoria|autoridad superior")~ "PLANTA TRANSITORIA",
    TRUE ~ NA
  )) |> 
  mutate(estructura = str_extract(cargo,"Direccion.+|coordinacion.+|Comisión.+|Secretaría de.+|Coordinación .+|Subsecretaría de.+|Subsecretaria de,+")) |> 
  mutate(cargo =str_squish( str_remove_all(cargo, estructura)) )|> 
  mutate(cargo = str_remove_all(cargo,"de\r\nla $|de la $ |de la$")) |> 
  mutate(ingreso_cargo=ammend_date_3(original_dates =  ingreso_cargo)) |> 
  mutate(primer_registro_cargo = ingreso_cargo) |> 
  mutate(organismo = "JEFATURA DE GABINETE", fuente = "PDI", poder="EJECUTIVO", nombre =NA, apellido = NA, baja_cargo = NA) |> 
 relocate(dni, nombre_completo, apellido, nombre,  cargo,   tipo_contratacion, organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo) |> 
  mutate_if(is.character, str_to_upper)|> 
   mutate_if(is.character,remove_accents) |> 
  arrange(desc(ultimo_registro_cargo)) |> 
  distinct(dni, .keep_all = TRUE) |> 
  mutate(ingreso_cargo=as.Date(ingreso_cargo), primer_registro_cargo = as.Date(primer_registro_cargo)) |> 
  mutate(primer_registro_cargo=if_else(is.na(primer_registro_cargo),as.Date("2024-09-01"), primer_registro_cargo) )->interim_certificaciones_servicios_sec_ambiente_turismo_deportes_min_interior_sep_dec_2024
  
  
```



#Secretaria presidencia       
```{r}
external_empleados_locacion_sec_presidencia_feb_2025 |> 
  rename(dni = CUIL, apellido = APELLIDO, nombre =NOMBRE,estructura = SECRETARIA, baja_cargo = FECHA, ingreso_cargo = `FECHA DE INGRESO SGP`) |> 
  select(-`SECRETARÍA/SUBSECRETARÍA`,-BAJA) |> 
  mutate(dni = str_remove_all(dni,"^..")) |> 
  mutate(dni = str_remove_all(dni,".$")) |> 
  mutate(nombre_completo = paste(nombre, apellido)) |> 
  mutate(primer_registro_cargo = ingreso_cargo) |> 
  mutate(ultimo_registro_cargo = case_when(
    !is.na(baja_cargo)~ as.Date(baja_cargo),
    TRUE~ as.Date("2025-02-28")
  )) |> 
   mutate(organismo = "SECRETARIA DE PRESIDENCIA", tipo_contratacion = "LOCACION",fuente = "PDI", poder="EJECUTIVO") |> 
  relocate(dni, nombre_completo,apellido, nombre,  tipo_contratacion,organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo, poder, fuente) |> 
  mutate_if(is.character, str_to_upper)|> 
   mutate_if(is.character,remove_accents) |> 
  distinct(dni, .keep_all = TRUE)->interim_empleados_locacion_sec_presidencia_feb_2025
  
```


```{r}
#PEN

#Editamos para poder unir
colnames(external_empleados_pen_agosto_2023 )<-str_to_lower(colnames(external_empleados_pen_agosto_2023))
external_empleados_pen_agosto_2023 |> 
  mutate(doc = str_remove_all(cuil,"^..")) |> 
  mutate(doc = str_remove_all(doc,".$")) |> 
  mutate(doc = str_remove_all(doc,"^0")) |> 
  select(-cuil,-cfu_org) |> 
  rename(periodo = ultimo_registro)->auxiliar_2023

bind_rows(external_empleados_pen_mayo_2025,external_empleados_pen_abril_2025, external_empleados_pen_marzo_2025, external_empleados_pen_febrero_2025 ,external_empleados_pen_diciembre_2024, external_empleados_pen_noviembre_2024, external_empleados_pen_octubre_2024,
          external_empleados_pen_septiembre_2024, external_empleados_pen_agosto_2024, auxiliar_2023) |> 
  mutate(doc = as.character(doc)) |> 
  distinct(doc, .keep_all = TRUE)->descartar

descartar|> 
  rename(ultimo_registro_cargo = periodo) |> 
  left_join(auxiliar_2023 |> distinct(doc, periodo), by = "doc") |> 
  left_join(external_empleados_pen_agosto_2024 |> distinct(doc, periodo), by = "doc") |> 
  left_join(external_empleados_pen_septiembre_2024 |> distinct(doc, periodo), by = "doc") |> 
  left_join(external_empleados_pen_octubre_2024 |> distinct(doc, periodo), by = "doc") |> 
  left_join(external_empleados_pen_noviembre_2024|> distinct(doc, periodo), by = "doc")  |> 
  left_join(external_empleados_pen_diciembre_2024|> distinct(doc, periodo), by = "doc")  |> 
  left_join(external_empleados_pen_febrero_2025|> distinct(doc, periodo), by = "doc")  |> 
   left_join(external_empleados_pen_marzo_2025|> distinct(doc, periodo), by = "doc")  |> 
  left_join(external_empleados_pen_abril_2025|> distinct(doc, periodo), by = "doc")  |> 
  distinct(doc, .keep_all = TRUE) |> 
  mutate(primer_registro_cargo = case_when(
    !is.na(periodo.x)~ periodo.x,
    !is.na(periodo.y)~ periodo.y,
    !is.na(periodo.x.x)~ periodo.x.x,
    !is.na(periodo.y.y)~ periodo.y.y,
    !is.na(periodo.x.x.x)~ periodo.x.x.x,
    !is.na(periodo.y.y.y)~ periodo.y.y.y,
    !is.na(periodo.x.x.x.x)~ periodo.x.x.x.x,
    !is.na(periodo.y.y.y.y)~ periodo.y.y.y.y,
    !is.na(periodo)~periodo,
    TRUE ~ 202505
  )) |> 
  select(-periodo.x, -periodo.y,-periodo.x.x,-periodo.y.y,-periodo.x.x.x,-periodo.y.y.y,-periodo.x.x.x.x,-periodo.y.y.y.y, -periodo) |> 
  mutate(apellido_y_nombre = str_remove_all(apellido_y_nombre, "(?<=\\s)DE(?=\\s)|(?<=\\s).(?=\\s)|\\(.+\\)")) |> 
  mutate(nombre_completo = case_when(
    str_detect(apellido_y_nombre, ".+\\s.+\\s.+\\s.+$") ~ str_replace_all(apellido_y_nombre, "(.+)\\s(.+)\\s(.+)\\s(.+)$", "\\3 \\4 \\1 \\2"),
    str_detect(apellido_y_nombre, ".+\\s.+\\s.+$") ~ str_replace_all(apellido_y_nombre, "(.+)\\s(.+)\\s(.+)$", "\\2 \\3 \\1"),
    str_detect(apellido_y_nombre, ".+\\s.+$") ~ str_replace_all(apellido_y_nombre, "(.+)\\s(.+)$", "\\2 \\1"),
    TRUE ~ apellido_y_nombre
  )) |> 
  select(-apellido_y_nombre,-telefono) |> 
  rename(dni = doc, categoria_cargo = escalafon) |> 
    relocate(nombre_completo, .after = dni) |> 
    mutate(tipo_contratacion = case_when(
      str_detect(tipo_contratacion,"SERVICIO|CONTRATADO")~ "LOCACION",
      str_detect(tipo_contratacion,"PERMANENTE Y TRANSITORIA") ~ "PERMANENTE O TRANSITORIA",
      TRUE~ tipo_contratacion
    )) |> 
    mutate(fecha_de_nacimiento = NA, apellido = NA, nombre = NA, cargo = NA, legajo = NA, ingreso_cargo = NA, baja_cargo = NA, estructura = NA) |> 
    mutate(poder = "EJECUTIVO", fuente = "BIEP") |> 
    relocate(dni, nombre_completo, apellido, nombre, fecha_de_nacimiento, cargo, legajo, categoria_cargo, tipo_contratacion, organismo, estructura, ingreso_cargo, baja_cargo, primer_registro_cargo, ultimo_registro_cargo) |> 
  mutate(primer_registro_cargo = paste0(primer_registro_cargo,"-01")) |> 
  mutate(primer_registro_cargo = str_replace_all(primer_registro_cargo,"^(....)","\\1-")) |> 
  mutate(ultimo_registro_cargo = paste0(ultimo_registro_cargo, "-28")) |> 
  mutate(ultimo_registro_cargo = str_replace_all(ultimo_registro_cargo, "^(....)", "\\1-")) |> 
  mutate(primer_registro_cargo = as.Date(primer_registro_cargo),
         ultimo_registro_cargo = as.Date(ultimo_registro_cargo))|> 
  filter(!str_detect(categoria_cargo,"JUDICIAL")) |> 
  mutate_if(is.character,str_to_upper)|> 
   mutate_if(is.character,remove_accents)->interim_empleados_apn_2023_2025
```

```{r}
bind_rows( interim_empleados_apn_2023_2025,interim_empleados_locacion_defensa_2019_2023,interim_certificaciones_servicios_min_defensa_sept_dic_2024,
           interim_empleados_ambiente_2024, interim_empleados_deporte_2024, interim_empleados_locacion_seguridad_2020_2024, interim_empleados_ministerio_interior, interim_empleados_locacion_min_capital_humano_2024, interim_empleados_locacion_min_exteriores_2022_2025, interim_certificaciones_servicios_min_exteriores_sept_2024_jun_2025,interim_empleados_locacion_min_salud_2019_2024,interim_empleados_locacion_jefatura_2019_2024,interim_empleados_locacion_sec_presidencia_feb_2025,interim_empleados_min_justicia_2024,interim_certificaciones_servicios_sec_ambiente_turismo_deportes_min_interior_sep_dec_2024,interim_empleados_certificaciones_jefatura_2024) |> 
  #OJO NO QUITAMOS DNIS REPETIDOOS PORQUE PUEDE TRATARSE DE PERSONAS DIFERENTES
  #distinct(dni, .keep_all=TRUE) |> 
  mutate_if(is.character,str_squish)|> 
  arrange(desc(ultimo_registro_cargo))->processed_empleados_ejecutivo
```

#Saving
```{r}
write.csv(processed_empleados_judicial,"../../../data/processed/employees/processed_empleados_judicial.csv")
drive_update(as_id("1ng8ZeDJrLiUq9DcR82CYBg4vlGU2TDxH"),"../../../data/processed/employees/processed_empleados_judicial.csv")
file.remove("../../../data/processed/employees/processed_empleados_judicial.csv")

write.csv(processed_empleados_legislativo,"../../../data/processed/employees/processed_empleados_legislativo.csv")
drive_update(as_id("1OtarWp_Yxf8Lj2paATMot5f2uAC3rAWL"),"../../../data/processed/employees/processed_empleados_legislativo.csv")
file.remove("../../../data/processed/employees/processed_empleados_legislativo.csv")

write.csv(processed_empleados_ejecutivo,"../../../data/processed/employees/processed_empleados_ejecutivo.csv")
drive_update(as_id("1y0jXMd3jAnDetdp1fr-jXBOIeuhgSFUK"),"../../../data/processed/employees/processed_empleados_ejecutivo.csv")
file.remove("../../../data/processed/employees/processed_empleados_ejecutivo.csv")

```



